# Generated by Django 4.1.7 on 2023-02-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='pet_name',
            field=models.CharField(default='nameless', max_length=20),
        ),
    ]
